apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy everything with:  kubectl apply -k k8s/
namespace: roomnest

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - backend.yaml
  - frontend.yaml
